window._env_ = {
	// API_KEY: 'CC2RXHP-TB2M9ZJ-NKZEBHK-WQPHD5G',
	// API_KEY: 'AAA5ZFN-TN748W0-QX3DWZZ-MEFRVT5',
	//тариф student
	API_KEY: 'AAA5ZFN-TN748W0-QX3DWZZ-MEFRVT5',
	API_URL: 'https://api.kinopoisk.dev',
	API_VERSION: 'v1.4'
}
